[package]
name = "bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "package-release"


[dependencies]
anyhow = "1.0"
current_platform = "0.2"
chrono = "0.4"
flate2 = "1.0"
reqwest = { version = "0.12", default-features = false, features = ["blocking", "default-tls"] }
rusty-s3 = { version = "0.5", default-features = false }
tar = "0.4"
walkdir = "2.5"
zip = { version = "1.1", default-features = false }