[package]
name = "dose-response"
version = "0.1.0"
authors = ["Tomas Sedovic <tomas@sedovic.cz>"]

[[bin]]
name = "dose-response"
path = "src/main.rs"

[dependencies]
time = "0.1.34"
rand = "0.3.13"
tcod = "0.9"
rustbox = "0.8.0"
