[package]

name = "dose-response"
version = "0.1.0"
authors = ["Tomas Sedovic <tomas@sedovic.cz>"]

[[bin]]

name = "dose-response"
path = "src/main.rs"

[dependencies.emhyr]

path = "../emhyr"

[dependencies.tcod]

git = "https://github.com/tomassedovic/tcod-rs.git"