[package]
name = "dose-response"
version = "0.3.0"
authors = ["Tomas Sedovic <tomas@sedovic.cz>"]

[[bin]]
name = "dose-response"
path = "src/main.rs"

[dependencies]
time = "0.1.35"
rand = "0.3.14"
clap = "2.20.1"

tcod = { git = "https://github.com/tomassedovic/tcod-rs", optional = true }
rustbox = { version = "0.9.0", optional = true }
piston_window = { version = "0.63.0", optional = true }
image = { version = "0.12.2", optional = true }
glium = { version = "0.16.0", optional = true }


[features]

default = ["opengl"]

piston = ["piston_window", "image"]

opengl = ["glium", "image"]

terminal = ["rustbox"]

libtcod = ["tcod"]
