[package]
name = "dose-response"
version = "0.1.0"
authors = ["Tomas Sedovic <tomas@sedovic.cz>"]

[[bin]]
name = "dose-response"
path = "src/main.rs"

[dependencies]
time = "0.1.25"
rand = "0.3.8"
tcod = "0.6.0"
tcod-sys = "2.0.11"
