[package]
name = "dose-response"
version = "0.1.0"
authors = ["Tomas Sedovic <tomas@sedovic.cz>"]

[[bin]]
name = "dose-response"
path = "src/main.rs"

[dependencies]
time = "0.1.24"
rand = "0.3.7"
tcod = "0.5.5"
tcod-sys = "2.0.10"
