[package]
name = "dose-response"
version = "0.1.0"
authors = ["Tomas Sedovic <tomas@sedovic.cz>"]

[[bin]]
name = "dose-response"
path = "src/main.rs"


[dependencies]
time = "*"
tcod = "*"


# TODO: temporarily disabling debuginfo until this is fixed:
# https://github.com/rust-lang/rust/issues/17257
[profile.dev]
debug = false
