[package]
name = "dose-response"
version = "0.3.0"
authors = ["Tomas Sedovic <tomas@sedovic.cz>"]

[[bin]]
name = "dose-response"
path = "src/main.rs"

[dependencies]
time = "0.1.35"
rand = "0.3.14"
tcod = { git = "https://github.com/tomassedovic/tcod-rs" }
# rustbox = "0.8.0"
piston_window = "0.63.0"
image = "0.12.2"
glium = "0.16.0"
clap = "2.20.1"
