[package]
name = "dose-response"
version = "0.1.0"
authors = ["Tomas Sedovic <tomas@sedovic.cz>"]

[[bin]]
name = "dose-response"
path = "src/main.rs"


# [dependencies.tcod]
# path = "../tcod-rs"

# [dependencies.tcod-sys]
# path = "../tcod-rs/tcod-sys"

[dependencies]
time = "*"
rand = "*"
tcod = "*"
tcod-sys = "*"
