#[target.i686-pc-windows-gnu]
#rustflags = ["-C", "link-args=-mwindows"]

#[target.x86_64-pc-windows-gnu]
#rustflags = ["-C", "link-args=-mwindows"]

[target.x86_64-pc-windows-msvc]
rustflags = ["-Ctarget-feature=+crt-static"]

[target.i686-pc-windows-msvc]
rustflags = ["-Ctarget-feature=+crt-static"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-Wl,-rpath=$ORIGIN/lib"]
